[build]
  # Commande pour compiler l'application React
  command = "npm install --legacy-peer-deps && npm run build"
  
  # Dossier contenant les fichiers compilés à déployer
  publish = "dist/public"
  
  # Variables d'environnement pour le build
  [build.environment]
    NODE_VERSION = "22"
    NPM_FLAGS = "--legacy-peer-deps"

# Redirections pour le routing SPA (Single Page Application)
# Exception pour la page admin de Decap CMS
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

# Toutes les autres URLs doivent pointer vers index.html pour que React Router fonctionne
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration pour forcer HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

